# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
=begin # 旧データ
YoutubeSongInfo.create(id:1,title:"サンプル",youtube_id:"b4VW1H_tcYM",time:"254","attr"=>"normal")
YoutubeSongInfo.create(id:2,title:"サンプル",youtube_id:"Il5aESm1ENE",time:"253","attr"=>"normal")
YoutubeSongInfo.create(id:3,title:"サンプル",youtube_id:"9DLMQkFHPXc",time:"258","attr"=>"normal")
#YoutubeSongInfo.create(id:4,title:"サンプル",youtube_id:"8LvQSKCsrvU",time:"260","attr"=>"normal")
YoutubeSongInfo.create(id:5,title:"サンプル",youtube_id:"zaJcAAWgHxE",time:"152","attr"=>"normal")
YoutubeSongInfo.create(id:6,title:"サンプル",youtube_id:"jmsDbvevxGo",time:"70","attr"=>"normal")
YoutubeSongInfo.create(id:7,title:"サンプル",youtube_id:"5Qi0WeXJlDs",time:"107","attr"=>"normal")
YoutubeSongInfo.create(id:8,title:"サンプル",youtube_id:"ek2guvUGyhc",time:"120","attr"=>"normal")
YoutubeSongInfo.create(id:9,title:"サンプル",youtube_id:"xTvJgK2UuD8",time:"208","attr"=>"normal")
YoutubeSongInfo.create(id:10,title:"サンプル",youtube_id:"8slFzuXhIzQ",time:"394","attr"=>"normal")
YoutubeSongInfo.create(id:11,title:"サンプル",youtube_id:"SjLOcTuy8bA",time:"105","attr"=>"normal")
YoutubeSongInfo.create(id:12,title:"サンプル",youtube_id:"-_85yOTrqbM",time:"121","attr"=>"normal")
YoutubeSongInfo.create(id:13,title:"サンプル",youtube_id:"nYOFZ0xonjc",time:"213","attr"=>"normal")
YoutubeSongInfo.create(id:14,title:"サンプル",youtube_id:"1EfraubDJUo",time:"283","attr"=>"normal")
YoutubeSongInfo.create(id:15,title:"サンプル",youtube_id:"Tri4KDe2goA",time:"102","attr"=>"normal")
YoutubeSongInfo.create(id:16,title:"サンプル",youtube_id:"1U6_I6ldSiQ",time:"228","attr"=>"normal")
YoutubeSongInfo.create(id:17,title:"サンプル",youtube_id:"QIa5hG6PXiw",time:"267","attr"=>"normal")
YoutubeSongInfo.create(id:18,title:"サンプル",youtube_id:"kpbRw1s1TCA",time:"165","attr"=>"normal")
YoutubeSongInfo.create(id:19,title:"サンプル",youtube_id:"RDU0PiAo8xM",time:"160","attr"=>"normal")
YoutubeSongInfo.create(id:20,title:"サンプル",youtube_id:"I3aovbIIfes",time:"118","attr"=>"normal")
YoutubeSongInfo.create(id:21,title:"サンプル",youtube_id:"9VN_gYB3-Zo",time:"163","attr"=>"normal")
YoutubeSongInfo.create(id:22,title:"サンプル",youtube_id:"5cGA_BZqoUI",time:"122","attr"=>"normal")
YoutubeSongInfo.create(id:23,title:"サンプル",youtube_id:"G3kUj5D8e94",time:"372","attr"=>"normal")
YoutubeSongInfo.create(id:24,title:"サンプル",youtube_id:"kay_QtxRXBc",time:"215","attr"=>"normal")
YoutubeSongInfo.create(id:25,title:"サンプル",youtube_id:"loCgSjCDgTg",time:"117","attr"=>"normal")
=end

# 新データ
#　メモ）rake db:migrate:reset　　　rake db:seed
YoutubeSongInfo.create(id:1,title:"サンプル",youtube_id:"lVOCkS3bvEM",time:"140","attr"=>"normal")
YoutubeSongInfo.create(id:2,title:"サンプル",youtube_id:"nEVY8-KBSHY",time:"351","attr"=>"normal")
YoutubeSongInfo.create(id:3,title:"サンプル",youtube_id:"5AxxhQddWlQ",time:"183","attr"=>"normal")
YoutubeSongInfo.create(id:4,title:"サンプル",youtube_id:"rsz3Md44uc0",time:"139","attr"=>"normal")
YoutubeSongInfo.create(id:5,title:"サンプル",youtube_id:"Ut6QwDSX_Cg",time:"183","attr"=>"normal")
YoutubeSongInfo.create(id:6,title:"サンプル",youtube_id:"Mk-IfGontME",time:"170","attr"=>"normal")
YoutubeSongInfo.create(id:7,title:"サンプル",youtube_id:"ug5gnlkdrlw",time:"171","attr"=>"normal")
YoutubeSongInfo.create(id:8,title:"サンプル",youtube_id:"6odXCoSuMGM",time:"98","attr"=>"normal")
YoutubeSongInfo.create(id:9,title:"サンプル",youtube_id:"EWGVI02jAPo",time:"91","attr"=>"normal")
YoutubeSongInfo.create(id:10,title:"サンプル",youtube_id:"flXSBjy9TVw",time:"191","attr"=>"normal")
YoutubeSongInfo.create(id:11,title:"サンプル",youtube_id:"mVjl25JymQQ",time:"110","attr"=>"normal")
YoutubeSongInfo.create(id:12,title:"サンプル",youtube_id:"Ahu19ZjQpXI",time:"123","attr"=>"normal")
YoutubeSongInfo.create(id:13,title:"サンプル",youtube_id:"SCawwxyzD2I",time:"98","attr"=>"normal")
YoutubeSongInfo.create(id:14,title:"サンプル",youtube_id:"H6OGDgZuQ4k",time:"181","attr"=>"normal")
YoutubeSongInfo.create(id:15,title:"サンプル",youtube_id:"NgVfoSKRcTo",time:"133","attr"=>"normal")
YoutubeSongInfo.create(id:16,title:"サンプル",youtube_id:"HEP6WQxHw6s",time:"183","attr"=>"normal")
YoutubeSongInfo.create(id:17,title:"サンプル",youtube_id:"VGy-iORdfc0",time:"77","attr"=>"normal")
YoutubeSongInfo.create(id:18,title:"サンプル",youtube_id:"li-rgTEEqVY",time:"111","attr"=>"normal")
YoutubeSongInfo.create(id:19,title:"サンプル",youtube_id:"8pQHUDcvvaU",time:"105","attr"=>"normal")
YoutubeSongInfo.create(id:20,title:"サンプル",youtube_id:"83raX1naYBU",time:"81","attr"=>"normal")
YoutubeSongInfo.create(id:21,title:"サンプル",youtube_id:"E1tN2TWX1LY",time:"108","attr"=>"normal")
YoutubeSongInfo.create(id:22,title:"サンプル",youtube_id:"xVHq-bTjL18",time:"109","attr"=>"normal")
YoutubeSongInfo.create(id:23,title:"サンプル",youtube_id:"mEgy-moS3LM",time:"133","attr"=>"normal")
YoutubeSongInfo.create(id:24,title:"サンプル",youtube_id:"akW0biEvEZw",time:"198","attr"=>"normal")
YoutubeSongInfo.create(id:25,title:"サンプル",youtube_id:"Ba0EMAk0yek",time:"79","attr"=>"normal")
YoutubeSongInfo.create(id:26,title:"サンプル",youtube_id:"QhP8YHN9dFQ",time:"173","attr"=>"normal")